### ISSUE TITLE
请问还会更新吗

### ISSUE THREAD

**Issue by ifanhua** [dipelta/live-plus-plus#1]
斗鱼无法获取直播流.   是否还会更新

**Comment by dipelta** [comment]
这个项目目前不会更新了

**Comment by ifanhua** [comment]
斗鱼无法获取 更新这个很麻烦吗?
可以捐助这个项目吗?

**Comment by dipelta** [comment]
新版本的获取方式没怎么关注，应该不会很麻烦，之前因为工作太忙了所以没时间搞。
原本我以为没人在意这个项目，毕竟各个直播平台也都有自己的客户端了。
很感谢你的关注，这对我来说也是一种动力，既然有用户使用，那我也会在近期抽时间更新这个工程，时间可能在5月份，敬请期待

**Comment by dipelta** [comment]
@ifanhua 你好，v2.0.0的预览版已经发布了，感谢你的关注，预览版可能还存在一些问题，后续依旧可以通过Issues的方式进行交流
